
spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://120.26.173.108:33306/yulinu?characterEncoding=utf-8
    username: root
    password: yulinu_123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8088

